{{- if and .Values.auth.storageState (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "family-link-exporter.sessionSecretName" . }}
  labels:
    {{- include "family-link-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.key }}: |
{{ .Values.auth.storageState | indent 4 }}
{{- end }}
