name: Build family-link-exporter

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - docker/**
      - VERSION
      - .github/workflows/**

jobs:
  build-family-link-exporter:
    name: "Build family-link-exporter"
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/docker-publish.yml
    permissions:
      contents: read
      id-token: write
      packages: write
    secrets: inherit
    with:
      APP_NAME: family-link-exporter
      APP_DIR: docker
